# coding: utf-8

"""
    External Databases Query API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from external_data_query_microservice.models.drug_indication_request import \
    DrugIndicationRequest


class TestDrugIndicationRequest(unittest.TestCase):
    """DrugIndicationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DrugIndicationRequest:
        """Test DrugIndicationRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DrugIndicationRequest`
        """
        model = DrugIndicationRequest()
        if include_optional:
            return DrugIndicationRequest(
                filters = None,
                order_by = '',
                limit = 56,
                job_id = None
            )
        else:
            return DrugIndicationRequest(
        )
        """

    def testDrugIndicationRequest(self):
        """Test DrugIndicationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
