# coding: utf-8

"""
    External Databases Query API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from external_data_query_microservice.models.evalue_cutoff import EvalueCutoff


class TestEvalueCutoff(unittest.TestCase):
    """EvalueCutoff unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvalueCutoff:
        """Test EvalueCutoff
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EvalueCutoff`
        """
        model = EvalueCutoff()
        if include_optional:
            return EvalueCutoff(
            )
        else:
            return EvalueCutoff(
        )
        """

    def testEvalueCutoff(self):
        """Test EvalueCutoff"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
