# coding: utf-8

"""
    NoLabs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nolabs_microservice.models.get_jobs_list_for_target_ligand_response import GetJobsListForTargetLigandContentResponse

class TestGetJobsListForTargetLigandContentResponse(unittest.TestCase):
    """GetJobsListForTargetLigandContentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetJobsListForTargetLigandContentResponse:
        """Test GetJobsListForTargetLigandContentResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetJobsListForTargetLigandContentResponse`
        """
        model = GetJobsListForTargetLigandContentResponse()
        if include_optional:
            return GetJobsListForTargetLigandContentResponse(
                jobs_list = None
            )
        else:
            return GetJobsListForTargetLigandContentResponse(
                jobs_list = None,
        )
        """

    def testGetJobsListForTargetLigandContentResponse(self):
        """Test GetJobsListForTargetLigandContentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
