# coding: utf-8

"""
    NoLabs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nolabs_microservice.models.get_job_binding_pocket_data_response import GetJobBindingPocketDataResponse

class TestGetJobBindingPocketDataResponse(unittest.TestCase):
    """GetJobBindingPocketDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetJobBindingPocketDataResponse:
        """Test GetJobBindingPocketDataResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetJobBindingPocketDataResponse`
        """
        model = GetJobBindingPocketDataResponse()
        if include_optional:
            return GetJobBindingPocketDataResponse(
                pocket_ids = None
            )
        else:
            return GetJobBindingPocketDataResponse(
                pocket_ids = None,
        )
        """

    def testGetJobBindingPocketDataResponse(self):
        """Test GetJobBindingPocketDataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
