# coding: utf-8

"""
    NoLabs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nolabs_microservice.api.protein_design_api import ProteinDesignApi


class TestProteinDesignApi(unittest.TestCase):
    """ProteinDesignApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProteinDesignApi()

    def tearDown(self) -> None:
        pass

    def test_change_experiment_name_api_v1_protein_design_change_experiment_name_post(self) -> None:
        """Test case for change_experiment_name_api_v1_protein_design_change_experiment_name_post

        Change Experiment Name
        """
        pass

    def test_create_experiment_api_v1_protein_design_create_experiment_get(self) -> None:
        """Test case for create_experiment_api_v1_protein_design_create_experiment_get

        Create Experiment
        """
        pass

    def test_delete_experiment_api_v1_protein_design_experiment_delete(self) -> None:
        """Test case for delete_experiment_api_v1_protein_design_experiment_delete

        Delete Experiment
        """
        pass

    def test_experiments_api_v1_protein_design_experiments_metadata_get(self) -> None:
        """Test case for experiments_api_v1_protein_design_experiments_metadata_get

        Experiments
        """
        pass

    def test_get_experiment_api_v1_protein_design_experiment_get(self) -> None:
        """Test case for get_experiment_api_v1_protein_design_experiment_get

        Get Experiment
        """
        pass

    def test_inference_api_v1_protein_design_inference_post(self) -> None:
        """Test case for inference_api_v1_protein_design_inference_post

        Inference
        """
        pass


if __name__ == '__main__':
    unittest.main()
