# coding: utf-8

"""
    NoLabs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nolabs_microservice.models.delete_docking_job_response import DeleteDockingJobResponse

class TestDeleteDockingJobResponse(unittest.TestCase):
    """DeleteDockingJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteDockingJobResponse:
        """Test DeleteDockingJobResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteDockingJobResponse`
        """
        model = DeleteDockingJobResponse()
        if include_optional:
            return DeleteDockingJobResponse(
                job_id = None
            )
        else:
            return DeleteDockingJobResponse(
                job_id = None,
        )
        """

    def testDeleteDockingJobResponse(self):
        """Test DeleteDockingJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
