# coding: utf-8

"""
    NoLabs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nolabs_microservice.models.check_bio_buddy_enabled_response import CheckBioBuddyEnabledResponse

class TestCheckBioBuddyEnabledResponse(unittest.TestCase):
    """CheckBioBuddyEnabledResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckBioBuddyEnabledResponse:
        """Test CheckBioBuddyEnabledResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckBioBuddyEnabledResponse`
        """
        model = CheckBioBuddyEnabledResponse()
        if include_optional:
            return CheckBioBuddyEnabledResponse(
                enabled = None
            )
        else:
            return CheckBioBuddyEnabledResponse(
                enabled = None,
        )
        """

    def testCheckBioBuddyEnabledResponse(self):
        """Test CheckBioBuddyEnabledResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
