# coding: utf-8

"""
    NoLabs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nolabs_microservice.models.nolabs_api_models_amino_acid_localisation_amino_acid_response import NolabsApiModelsAminoAcidLocalisationAminoAcidResponse

class TestNolabsApiModelsAminoAcidLocalisationAminoAcidResponse(unittest.TestCase):
    """NolabsApiModelsAminoAcidLocalisationAminoAcidResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NolabsApiModelsAminoAcidLocalisationAminoAcidResponse:
        """Test NolabsApiModelsAminoAcidLocalisationAminoAcidResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NolabsApiModelsAminoAcidLocalisationAminoAcidResponse`
        """
        model = NolabsApiModelsAminoAcidLocalisationAminoAcidResponse()
        if include_optional:
            return NolabsApiModelsAminoAcidLocalisationAminoAcidResponse(
                sequence = None,
                name = None,
                cytosolic_proteins = None,
                mitochondrial_proteins = None,
                nuclear_proteins = None,
                other_proteins = None,
                extracellular_secreted_proteins = None
            )
        else:
            return NolabsApiModelsAminoAcidLocalisationAminoAcidResponse(
                sequence = None,
                name = None,
                cytosolic_proteins = None,
                mitochondrial_proteins = None,
                nuclear_proteins = None,
                other_proteins = None,
                extracellular_secreted_proteins = None,
        )
        """

    def testNolabsApiModelsAminoAcidLocalisationAminoAcidResponse(self):
        """Test NolabsApiModelsAminoAcidLocalisationAminoAcidResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
