# coding: utf-8

"""
    NoLabs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nolabs_microservice.models.run_simulations_response import RunSimulationsResponse

class TestRunSimulationsResponse(unittest.TestCase):
    """RunSimulationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunSimulationsResponse:
        """Test RunSimulationsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunSimulationsResponse`
        """
        model = RunSimulationsResponse()
        if include_optional:
            return RunSimulationsResponse(
                experiment_id = None,
                experiment_name = None,
                timeline = None,
                pdb_content = None
            )
        else:
            return RunSimulationsResponse(
                experiment_id = None,
                experiment_name = None,
                timeline = None,
        )
        """

    def testRunSimulationsResponse(self):
        """Test RunSimulationsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
