# coding: utf-8

"""
    NoLabs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nolabs_microservice.models.rcsb_pdb_meta_data import RcsbPdbMetaData

class TestRcsbPdbMetaData(unittest.TestCase):
    """RcsbPdbMetaData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RcsbPdbMetaData:
        """Test RcsbPdbMetaData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RcsbPdbMetaData`
        """
        model = RcsbPdbMetaData()
        if include_optional:
            return RcsbPdbMetaData(
                link = None
            )
        else:
            return RcsbPdbMetaData(
                link = None,
        )
        """

    def testRcsbPdbMetaData(self):
        """Test RcsbPdbMetaData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
