# coding: utf-8

"""
    NoLabs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nolabs_microservice.models.target_meta_data import TargetMetaData

class TestTargetMetaData(unittest.TestCase):
    """TargetMetaData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TargetMetaData:
        """Test TargetMetaData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TargetMetaData`
        """
        model = TargetMetaData()
        if include_optional:
            return TargetMetaData(
                target_id = None,
                target_name = None,
                link = None,
                folding_method = None
            )
        else:
            return TargetMetaData(
                target_id = None,
                target_name = None,
        )
        """

    def testTargetMetaData(self):
        """Test TargetMetaData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
