# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from msa_light_microservice.models.http_validation_error import HTTPValidationError
from msa_light_microservice.models.run_msa_prediction_request import RunMsaPredictionRequest
from msa_light_microservice.models.run_msa_prediction_response import RunMsaPredictionResponse
from msa_light_microservice.models.validation_error import ValidationError
from msa_light_microservice.models.validation_error_loc_inner import ValidationErrorLocInner
