# coding: utf-8

"""
    Solubility api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solubility_microservice.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_run_solubility_run_solubility_prediction_post(self) -> None:
        """Test case for run_solubility_run_solubility_prediction_post

        Run Solubility
        """


if __name__ == "__main__":
    unittest.main()
