# coding: utf-8

"""
    Reinvent4 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reinvent_microservice.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_fine_tuning_get_all_jobs_jobs_get(self) -> None:
        """Test case for fine_tuning_get_all_jobs_jobs_get

        Fine Tuning Get All Jobs
        """
        pass

    def test_get_job_jobs_job_id_get(self) -> None:
        """Test case for get_job_jobs_job_id_get

        Get Job
        """
        pass

    def test_logs_jobs_job_id_logs_get(self) -> None:
        """Test case for logs_jobs_job_id_logs_get

        Logs
        """
        pass

    def test_params_jobs_job_id_params_get(self) -> None:
        """Test case for params_jobs_job_id_params_get

        Params
        """
        pass

    def test_prepare_binder_prepare_binder_post(self) -> None:
        """Test case for prepare_binder_prepare_binder_post

        Prepare Binder
        """
        pass

    def test_run_jobs_run_post(self) -> None:
        """Test case for run_jobs_run_post

        Run
        """
        pass

    def test_smiles_jobs_job_id_smiles_get(self) -> None:
        """Test case for smiles_jobs_job_id_smiles_get

        Smiles
        """
        pass


if __name__ == '__main__':
    unittest.main()
