# coding: utf-8

"""
    Reinvent4 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reinvent_microservice.models.response_get_config_api_reinvent_reinvent_config_id_get import ResponseGetConfigApiReinventReinventConfigIdGet

class TestResponseGetConfigApiReinventReinventConfigIdGet(unittest.TestCase):
    """ResponseGetConfigApiReinventReinventConfigIdGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseGetConfigApiReinventReinventConfigIdGet:
        """Test ResponseGetConfigApiReinventReinventConfigIdGet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseGetConfigApiReinventReinventConfigIdGet`
        """
        model = ResponseGetConfigApiReinventReinventConfigIdGet()
        if include_optional:
            return ResponseGetConfigApiReinventReinventConfigIdGet(
                id = None,
                name = None,
                created_at = None,
                running = None,
                sampling_allowed = None
            )
        else:
            return ResponseGetConfigApiReinventReinventConfigIdGet(
                id = None,
                name = None,
                created_at = None,
                running = None,
                sampling_allowed = None,
        )
        """

    def testResponseGetConfigApiReinventReinventConfigIdGet(self):
        """Test ResponseGetConfigApiReinventReinventConfigIdGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
