services:
  mongo:
    image: 'mongo:latest'
    network_mode: host
  redis:
    image: 'redis:latest'
    network_mode: host
  esmfold:
    image: 'ghcr.io/basedlabs/esmfold:2.0.0'
    network_mode: host
    build:
      context: microservices/esmfold
      dockerfile: build/Dockerfile
    command: python3 worker.py
    env_file:
      - microservices/esmfold/service/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  esmfold-light:
    image: 'ghcr.io/basedlabs/esmfold-light:2.0.0'
    network_mode: host
    command: python worker.py
    build:
      context: microservices/esmfold_light
      dockerfile: build/Dockerfile
    env_file:
      - microservices/esmfold_light/service/.env
  protein-design:
    image: 'ghcr.io/basedlabs/protein-design:1.1.0'
    network_mode: host
    build:
      context: microservices/rfdiffusion
      dockerfile: build/Dockerfile
    command: --host=0.0.0.0 --port=5789
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  diffdock:
    image: 'ghcr.io/basedlabs/diffdock:2.0.1'
    network_mode: host
    build:
      context: microservices/diffdock
      dockerfile: build/Dockerfile
    command: python worker.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    env_file:
      - microservices/diffdock/service/.env
    volumes:
      - ${DIFFDOCK_WEIGHTS_LOCATION}:/app/DiffDock/esm/model_weights/.cache/torch/hub/checkpoints
  external-data-query:
    image: 'ghcr.io/basedlabs/external-data-query:1.0.3'
    network_mode: host
    build:
      context: microservices/external_data_query
      dockerfile: build/Dockerfile
    command: --host=0.0.0.0 --port=5739
  biobuddy:
    image: 'ghcr.io/basedlabs/biobuddy:1.2.1'
    network_mode: host
    build:
      context: microservices/biobuddy
      dockerfile: build/Dockerfile
    env_file:
      - microservices/diffdock/service/.env
    command: --host=0.0.0.0 --port=5738
  rosettafold:
    image: 'ghcr.io/basedlabs/rosettafold:1.0.0'
    network_mode: host
    build:
      context: microservices/rosettafold
      dockerfile: build/Dockerfile
    volumes:
      - ${ROSETTAFOLD_BFD_PATH}:/RoseTTAFold/bfd
      - ${ROSETTAFOLD_PDB_PATH}:/RoseTTAFold/pdb100_2021Mar03
      - ${ROSETTAFOLD_UNIREF_PATH}:/RoseTTAFold/UniRef30_2020_06
    command: --host=0.0.0.0 --port=5738
  nolabs-api:
    image: 'ghcr.io/basedlabs/nolabs:2.1.7'
    network_mode: host
    build:
      context: .
      dockerfile: build/Dockerfile
    command: --host=0.0.0.0
  nolabs-worker:
    image: 'ghcr.io/basedlabs/nolabs-worker:1.0.0'
    network_mode: host
    build:
      context: .
      dockerfile: nolabs/build/worker.Dockerfile
    command: python workflow/worker.py

