services:
  conformations:
    build:
      context: microservices/conformations
      dockerfile: build/Dockerfile
    ports:
      - "5785:5785"
    command: --host=0.0.0.0 --port=5785
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  solubility:
    build:
      context: microservices/solubility
      dockerfile: build/Dockerfile
    ports:
      - "5786:5786"
    command: --host=0.0.0.0 --port=5786
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  protein_design:
    build:
      context: microservices/protein_design
      dockerfile: build/Dockerfile
    ports:
      - "5789:5789"
    command: --host=0.0.0.0 --port=5789
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  localisation:
    build:
      context: microservices/localisation
      dockerfile: build/Dockerfile
    ports:
      - "5787:5787"
    command: --host=0.0.0.0 --port=5787
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  gene_ontology:
    build:
      context: microservices/gene_ontology
      dockerfile: build/Dockerfile
    ports:
      - "5788:5788"
    command: --host=0.0.0.0 --port=5788
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  nolabs:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "8000:8000"
      - "9000:9000"
    command: --host=0.0.0.0 --port=5788
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]