services:
  conformations:
    build:
      context: microservices/conformations
      dockerfile: build/Dockerfile
    ports:
      - "5785:5785"
    command: --host=0.0.0.0 --port=5785
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  esmfold:
    build:
      context: microservices/esmfold
      dockerfile: build/Dockerfile
    ports:
      - "5736:5736"
    command: --host=0.0.0.0 --port=5736
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  esmfold_light:
    build:
      context: microservices/esmfold_light
      dockerfile: build/Dockerfile
    ports:
      - "5733:5733"
    command: --host=0.0.0.0 --port=5733
  solubility:
    build:
      context: microservices/solubility
      dockerfile: build/Dockerfile
    ports:
      - "5786:5786"
    command: --host=0.0.0.0 --port=5786
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  protein_design:
    build:
      context: microservices/protein_design
      dockerfile: build/Dockerfile
    ports:
      - "5789:5789"
    command: --host=0.0.0.0 --port=5789
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  localisation:
    build:
      context: microservices/localisation
      dockerfile: build/Dockerfile
    ports:
      - "5787:5787"
    command: --host=0.0.0.0 --port=5787
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  gene_ontology:
    build:
      context: microservices/gene_ontology
      dockerfile: build/Dockerfile
    command: --host=0.0.0.0 --port=5788
    ports:
      - "5788:5788"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  umol:
    build:
      context: microservices/umol
      dockerfile: build/Dockerfile
    ports:
      - "5735:5735"
    command: --host=0.0.0.0 --port=5735
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  diffdock:
    build:
      context: microservices/diffdock
      dockerfile: build/Dockerfile
    ports:
      - "5737:5737"
    command: --host=0.0.0.0 --port=5737
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  p2rank:
    build:
      context: microservices/p2rank
      dockerfile: build/Dockerfile
    ports:
      - "5731:5731"
    command: --host=0.0.0.0 --port=5731
  msa_light:
    build:
      context: microservices/msa_light
      dockerfile: build/Dockerfile
    ports:
      - "5734:5734"
    command: --host=0.0.0.0 --port=5734
  nolabs:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "8000:8000"
      - "9000:9000"
    command: --host=0.0.0.0
