services:
  conformations:
    build: microservices/conformations/build
    working_dir: microservices/conformations
    ports:
      - "5785:5785"
    command: --host=0.0.0.0 --port=5785
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  solubility:
    build: microservices/solubility/build
    working_dir: microservices/solubility
    ports:
      - "5786:5786"
    command: --host=0.0.0.0 --port=5786
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  protein_design:
    build: microservices/protein_design/build
    working_dir: microservices/protein_design
    ports:
      - "5789:5789"
    command: --host=0.0.0.0 --port=5789
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]