[tool.poetry]
name = "nolabsserver"
version = "0.1.0"
description = ""
authors = ["JaktensTid <jaktenstid1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
solubility-microservice = {path = "microservices/solubility/client"}
conformations-microservice = {path = "microservices/conformations/client"}
websockets = "^12.0"
uvicorn = "^0.25.0"

[project]
dependencies = [
    "fastapi",
    "mypy",
    "pydantic",
    "obonet",
    "jsonpickle"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
