[tool.poetry]
name = "nolabsserver"
version = "0.1.0"
description = ""
authors = ["JaktensTid <jaktenstid1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
solubility-microservice = {path = "microservices/solubility/client"}
conformations-microservice = {path = "microservices/conformations/client"}
p2rank-microservice = {path = "microservices/p2rank/client"}
esmfold-microservice = {path = "microservices/esmfold/client"}
esmfold_light-microservice = {path = "microservices/esmfold_light/client"}
umol-microservice = {path = "microservices/umol/client"}
msa_light-microservice = {path = "microservices/msa_light/client"}
websockets = "^12.0"
uvicorn = "^0.25.0"
fastapi = "^0.109.0"
numpy = "^1.26.3"
requests = "^2.31.0"
localisation-microservice = {path = "microservices/localisation/client"}

[project]
dependencies = [
    "fastapi",
    "mypy",
    "pydantic",
    "obonet",
    "jsonpickle",
    "python-multipart"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
