# coding: utf-8

"""
    External Databases Query API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from external_data_query_microservice.models.ch_embl_molecule_response import \
    ChEMBLMoleculeResponse


class TestChEMBLMoleculeResponse(unittest.TestCase):
    """ChEMBLMoleculeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChEMBLMoleculeResponse:
        """Test ChEMBLMoleculeResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ChEMBLMoleculeResponse`
        """
        model = ChEMBLMoleculeResponse()
        if include_optional:
            return ChEMBLMoleculeResponse(
                molecules = [
                    external_data_query_microservice.models.molecule.Molecule(
                        chembl_id = '', 
                        molecule_type = '', 
                        synonyms = [
                            ''
                            ], 
                        smiles = '', 
                        link = '', 
                        pref_name = '', )
                    ]
            )
        else:
            return ChEMBLMoleculeResponse(
                molecules = [
                    external_data_query_microservice.models.molecule.Molecule(
                        chembl_id = '', 
                        molecule_type = '', 
                        synonyms = [
                            ''
                            ], 
                        smiles = '', 
                        link = '', 
                        pref_name = '', )
                    ],
        )
        """

    def testChEMBLMoleculeResponse(self):
        """Test ChEMBLMoleculeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
