version = 4
run_type = "staged_learning"
use_cuda = true
output_csv = "rl_direct_.csv"

[parameters]
use_checkpoint = false  
summary_csv_prefix = "rl_direct"
agent_file = "/app/REINVENT4/priors/reinvent.prior"
prior_file = "/app/REINVENT4/priors/reinvent.prior"

batch_size = 1
uniquify_smiles = true   
randomize_smiles = true  

[learning_strategy]

type = "dap"    
sigma = 128      
rate = 0.0005     

[diversity_filter] 

type = "IdenticalMurckoScaffold" 
bucket_size = 50
minscore = 0.0

[[stage]]
chkpt_file = 'rl_direct.chkpt'
termination = "simple"
max_steps = 50

[stage.scoring]
type = "geometric_mean"

[[stage.scoring.component]]
[[stage.scoring.component.DockStream.endpoint]]
name = "Docking into 2XCH grid"
weight = 1
params.configuration_path = "/app/case_study_files/dockstream_rl_direct_uncs_dockvina.json"
params.docker_script_path = "/app/DockStream/docker.py"
params.docker_python_path =  "/var/conda/envs/DockStream/bin/python"
transform.type = "reverse_sigmoid"
transform.high = -7
transform.low = -13.5
transform.k = 0.2

[[stage.scoring.component]]
[stage.scoring.component.QED]
[[stage.scoring.component.QED.endpoint]]
name = "QED"
weight = 1