# Transfer learning on a set of related active compounds

run_type = "transfer_learning"
use_cuda = false
tb_logdir = "tb_TL"  

[parameters]

num_epochs = 10
save_every_n_epochs = 5 
batch_size = 50
num_refs = 50  
sample_batch_size = 50  

input_model_file = "reinvent.prior"
smiles_file = "AID_1798002_actives.smi"
output_model_file = "AID_1798002_actives.model"
validation_smiles_file = "AID_1798002_actives.smi"  
