# coding: utf-8

# flake8: noqa
"""
    Umol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from umol_microservice.models.http_validation_error import HTTPValidationError
from umol_microservice.models.run_umol_prediction_request import RunUmolPredictionRequest
from umol_microservice.models.run_umol_prediction_response import RunUmolPredictionResponse
from umol_microservice.models.validation_error import ValidationError
from umol_microservice.models.validation_error_loc_inner import ValidationErrorLocInner
