# coding: utf-8

"""
    Protein design api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RunRfdiffusionRequest(BaseModel):
    """
    RunRfdiffusionRequest
    """ # noqa: E501
    job_id: StrictStr
    pdb_content: StrictStr
    contig: StrictStr
    hotspots: Optional[StrictStr] = None
    timesteps: Optional[StrictInt] = None
    number_of_designs: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["job_id", "pdb_content", "contig", "hotspots", "timesteps", "number_of_designs"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RunRfdiffusionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if hotspots (nullable) is None
        # and model_fields_set contains the field
        if self.hotspots is None and "hotspots" in self.model_fields_set:
            _dict['hotspots'] = None

        # set to None if timesteps (nullable) is None
        # and model_fields_set contains the field
        if self.timesteps is None and "timesteps" in self.model_fields_set:
            _dict['timesteps'] = None

        # set to None if number_of_designs (nullable) is None
        # and model_fields_set contains the field
        if self.number_of_designs is None and "number_of_designs" in self.model_fields_set:
            _dict['number_of_designs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RunRfdiffusionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "job_id": obj.get("job_id"),
            "pdb_content": obj.get("pdb_content"),
            "contig": obj.get("contig"),
            "hotspots": obj.get("hotspots"),
            "timesteps": obj.get("timesteps"),
            "number_of_designs": obj.get("number_of_designs")
        })
        return _obj


