# coding: utf-8

"""
    RCSB PDB Query API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rcsb_pdb_query_microservice.models.get_fasta_files_by_search_query_request import GetFastaFilesBySearchQueryRequest

class TestGetFastaFilesBySearchQueryRequest(unittest.TestCase):
    """GetFastaFilesBySearchQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetFastaFilesBySearchQueryRequest:
        """Test GetFastaFilesBySearchQueryRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetFastaFilesBySearchQueryRequest`
        """
        model = GetFastaFilesBySearchQueryRequest()
        if include_optional:
            return GetFastaFilesBySearchQueryRequest(
                search_query = '',
                job_id = None
            )
        else:
            return GetFastaFilesBySearchQueryRequest(
                search_query = '',
        )
        """

    def testGetFastaFilesBySearchQueryRequest(self):
        """Test GetFastaFilesBySearchQueryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
