export type ErrorResponse = {
  errors: string[],
  error_code: number
}

export enum ErrorCodes {
  unknown_exception = 0,
  conformations_update_metadata_error = 1,
  amino_acid_solubility_run_error = 2,
  no_amino_acids = 3,
  experiment_not_found = 4,
  amino_acid_localisation_run_error = 5,
  protein_design_run_error = 6,
  protein_design_update_metadata_error = 7,
  drug_discovery_folding_error = 8,
  folding_method_unknown = 9,
  job_not_found = 10,
  invalid_aa_name = 11,
  invalid_aa_content = 12,
  invalid_protein_name = 13,
  invalid_protein_content = 14,
  invalid_protein_id = 15,
  invalid_aa_id = 16,
  invalid_experiment_id = 17,
  invalid_experiment_name = 18,
  invalid_job_id = 19,
  invalid_root_directory = 20,
  invalid_job_input = 21,
  invalid_job_name = 22,
  invalid_job_type = 23,
  invalid_job_context_id = 24,
  invalid_job_result = 25,
  duplicate_amino_acid = 26,
  unknown_localisation_error = 27,
  duplicate_protein = 28,
  invalid_localisation_job_output = 29,
  invalid_protein_solubility_probability = 30,
  no_domain_event_handler = 31,
  biobuddy_error_generating_response = 32,
  biobuddy_unexpected_message_type = 33,
  invalid_localisation_probability = 34
}
