# coding: utf-8

"""
    NoLabs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from nolabs_microservice.models.confidence import Confidence
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DiffDockLigandMetaData(BaseModel):
    """
    DiffDockLigandMetaData
    """ # noqa: E501
    job_id: Optional[Any]
    target_id: Optional[Any]
    ligand_id: Optional[Any]
    predicted_ligand_file_name: Optional[Any]
    minimized_affinity: Optional[Any]
    scored_affinity: Optional[Any]
    confidence: Optional[Confidence] = None
    __properties: ClassVar[List[str]] = ["job_id", "target_id", "ligand_id", "predicted_ligand_file_name", "minimized_affinity", "scored_affinity", "confidence"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DiffDockLigandMetaData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of confidence
        if self.confidence:
            _dict['confidence'] = self.confidence.to_dict()
        # set to None if job_id (nullable) is None
        # and model_fields_set contains the field
        if self.job_id is None and "job_id" in self.model_fields_set:
            _dict['job_id'] = None

        # set to None if target_id (nullable) is None
        # and model_fields_set contains the field
        if self.target_id is None and "target_id" in self.model_fields_set:
            _dict['target_id'] = None

        # set to None if ligand_id (nullable) is None
        # and model_fields_set contains the field
        if self.ligand_id is None and "ligand_id" in self.model_fields_set:
            _dict['ligand_id'] = None

        # set to None if predicted_ligand_file_name (nullable) is None
        # and model_fields_set contains the field
        if self.predicted_ligand_file_name is None and "predicted_ligand_file_name" in self.model_fields_set:
            _dict['predicted_ligand_file_name'] = None

        # set to None if minimized_affinity (nullable) is None
        # and model_fields_set contains the field
        if self.minimized_affinity is None and "minimized_affinity" in self.model_fields_set:
            _dict['minimized_affinity'] = None

        # set to None if scored_affinity (nullable) is None
        # and model_fields_set contains the field
        if self.scored_affinity is None and "scored_affinity" in self.model_fields_set:
            _dict['scored_affinity'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DiffDockLigandMetaData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "job_id": obj.get("job_id"),
            "target_id": obj.get("target_id"),
            "ligand_id": obj.get("ligand_id"),
            "predicted_ligand_file_name": obj.get("predicted_ligand_file_name"),
            "minimized_affinity": obj.get("minimized_affinity"),
            "scored_affinity": obj.get("scored_affinity"),
            "confidence": Confidence.from_dict(obj.get("confidence")) if obj.get("confidence") is not None else None
        })
        return _obj


