# coding: utf-8

"""
    BLAST Query

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from blast_query_microservice.models.blast_type import BlastType

class TestBlastType(unittest.TestCase):
    """BlastType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlastType(self):
        """Test BlastType"""
        # inst = BlastType()

if __name__ == '__main__':
    unittest.main()
