# coding: utf-8

"""
    Conformations api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ForceFields(str, Enum):
    """
    ForceFields
    """

    """
    allowed enum values
    """
    AMBER14_MINUS_ALL_DOT_XML = 'amber14-all.xml'
    AMBER14_SLASH_PROTEIN_DOT_FF14_SB_DOT_XML = 'amber14/protein.ff14SB.xml'
    AMBER14_SLASH_PROTEIN_DOT_FF15IPQ_DOT_XML = 'amber14/protein.ff15ipq.xml'
    AMBER14_SLASH_DNA_DOT_OL15_DOT_XML = 'amber14/DNA.OL15.xml'
    AMBER14_SLASH_DNA_DOT_BSC1_DOT_XML = 'amber14/DNA.bsc1.xml'
    AMBER14_SLASH_RNA_DOT_OL3_DOT_XML = 'amber14/RNA.OL3.xml'
    AMBER14_SLASH_LIPID17_DOT_XML = 'amber14/lipid17.xml'
    AMBER14_SLASH_GLYCAM_06J_MINUS_1_DOT_XML = 'amber14/GLYCAM_06j-1.xml'
    CHARMM36_DOT_XML = 'charmm36.xml'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ForceFields from a JSON string"""
        return cls(json.loads(json_str))


