# coding: utf-8

"""
    Conformations api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
from conformations_microservice.models.force_fields import ForceFields
from conformations_microservice.models.water_force_fields import WaterForceFields
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GenGroTopRequest(BaseModel):
    """
    GenGroTopRequest(*, forceField: conformations.api_models.ForceFields, waterForceField: conformations.api_models.WaterForceFields, pdbContent: str, ignoreMissingAtoms: bool = False)
    """ # noqa: E501
    force_field: ForceFields = Field(alias="forceField")
    water_force_field: WaterForceFields = Field(alias="waterForceField")
    pdb_content: StrictStr = Field(alias="pdbContent")
    ignore_missing_atoms: Optional[StrictBool] = Field(default=False, alias="ignoreMissingAtoms")
    __properties: ClassVar[List[str]] = ["forceField", "waterForceField", "pdbContent", "ignoreMissingAtoms"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GenGroTopRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GenGroTopRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "forceField": obj.get("forceField"),
            "waterForceField": obj.get("waterForceField"),
            "pdbContent": obj.get("pdbContent"),
            "ignoreMissingAtoms": obj.get("ignoreMissingAtoms") if obj.get("ignoreMissingAtoms") is not None else False
        })
        return _obj


