# coding: utf-8

"""
    Protein design api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from protein_design_microservice.models.run_rfdiffusion_request import RunRfdiffusionRequest

class TestRunRfdiffusionRequest(unittest.TestCase):
    """RunRfdiffusionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunRfdiffusionRequest:
        """Test RunRfdiffusionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunRfdiffusionRequest`
        """
        model = RunRfdiffusionRequest()
        if include_optional:
            return RunRfdiffusionRequest(
                pdb_content = '',
                hotspots = '',
                contig = '',
                timesteps = 56,
                number_of_designs = 56
            )
        else:
            return RunRfdiffusionRequest(
                pdb_content = '',
        )
        """

    def testRunRfdiffusionRequest(self):
        """Test RunRfdiffusionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
