# coding: utf-8

"""
    SC-GPT API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sc_gpt_microservice.models.reference_mapping_response import ReferenceMappingResponse

class TestReferenceMappingResponse(unittest.TestCase):
    """ReferenceMappingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReferenceMappingResponse:
        """Test ReferenceMappingResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReferenceMappingResponse`
        """
        model = ReferenceMappingResponse()
        if include_optional:
            return ReferenceMappingResponse(
                predictions = [
                    ''
                    ],
                accuracy = 1.337,
                precision = 1.337,
                recall = 1.337,
                macro_f1 = 1.337
            )
        else:
            return ReferenceMappingResponse(
                predictions = [
                    ''
                    ],
                accuracy = 1.337,
                precision = 1.337,
                recall = 1.337,
                macro_f1 = 1.337,
        )
        """

    def testReferenceMappingResponse(self):
        """Test ReferenceMappingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
