# coding: utf-8

"""
    SC-GPT API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sc_gpt_microservice.models.reference_mapping_request import ReferenceMappingRequest

class TestReferenceMappingRequest(unittest.TestCase):
    """ReferenceMappingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReferenceMappingRequest:
        """Test ReferenceMappingRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReferenceMappingRequest`
        """
        model = ReferenceMappingRequest()
        if include_optional:
            return ReferenceMappingRequest(
                query_path = '',
                reference_path = '',
                cell_type_key = '',
                gene_col = 'gene_name',
                batch_size = 56,
                device = 'cpu',
                k_neighbors = 56,
                calculate_metrics = True
            )
        else:
            return ReferenceMappingRequest(
                query_path = '',
                reference_path = '',
        )
        """

    def testReferenceMappingRequest(self):
        """Test ReferenceMappingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
