# coding: utf-8

"""
    SC-GPT API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sc_gpt_microservice.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_embed_embed_post(self) -> None:
        """Test case for embed_embed_post

        Embed
        """
        pass

    def test_reference_classify_reference_classify_post(self) -> None:
        """Test case for reference_classify_reference_classify_post

        Reference Classify
        """
        pass


if __name__ == '__main__':
    unittest.main()
