# coding: utf-8

"""
    SC-GPT API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sc_gpt_microservice.models.embed_request import EmbedRequest

class TestEmbedRequest(unittest.TestCase):
    """EmbedRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmbedRequest:
        """Test EmbedRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmbedRequest`
        """
        model = EmbedRequest()
        if include_optional:
            return EmbedRequest(
                dataset_path = '',
                gene_col = 'gene_name',
                batch_size = 56,
                device = 'cpu'
            )
        else:
            return EmbedRequest(
                dataset_path = '',
        )
        """

    def testEmbedRequest(self):
        """Test EmbedRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
