# coding: utf-8

# flake8: noqa
"""
    SC-GPT API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from sc_gpt_microservice.models.embed_request import EmbedRequest
from sc_gpt_microservice.models.embed_response import EmbedResponse
from sc_gpt_microservice.models.http_validation_error import HTTPValidationError
from sc_gpt_microservice.models.reference_mapping_request import ReferenceMappingRequest
from sc_gpt_microservice.models.reference_mapping_response import ReferenceMappingResponse
from sc_gpt_microservice.models.validation_error import ValidationError
from sc_gpt_microservice.models.validation_error_loc_inner import ValidationErrorLocInner
