# coding: utf-8

"""
    SC-GPT API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ReferenceMappingResponse(BaseModel):
    """
    ReferenceMappingResponse
    """ # noqa: E501
    predictions: List[StrictStr]
    accuracy: Optional[Union[StrictFloat, StrictInt]]
    precision: Optional[Union[StrictFloat, StrictInt]]
    recall: Optional[Union[StrictFloat, StrictInt]]
    macro_f1: Optional[Union[StrictFloat, StrictInt]]
    __properties: ClassVar[List[str]] = ["predictions", "accuracy", "precision", "recall", "macro_f1"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReferenceMappingResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if accuracy (nullable) is None
        # and model_fields_set contains the field
        if self.accuracy is None and "accuracy" in self.model_fields_set:
            _dict['accuracy'] = None

        # set to None if precision (nullable) is None
        # and model_fields_set contains the field
        if self.precision is None and "precision" in self.model_fields_set:
            _dict['precision'] = None

        # set to None if recall (nullable) is None
        # and model_fields_set contains the field
        if self.recall is None and "recall" in self.model_fields_set:
            _dict['recall'] = None

        # set to None if macro_f1 (nullable) is None
        # and model_fields_set contains the field
        if self.macro_f1 is None and "macro_f1" in self.model_fields_set:
            _dict['macro_f1'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReferenceMappingResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "predictions": obj.get("predictions"),
            "accuracy": obj.get("accuracy"),
            "precision": obj.get("precision"),
            "recall": obj.get("recall"),
            "macro_f1": obj.get("macro_f1")
        })
        return _obj


