# coding: utf-8

"""
    Gene ontology api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gene_ontology_microservice.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_run_go_prediction_run_go_prediction_post(self) -> None:
        """Test case for run_go_prediction_run_go_prediction_post

        Run Go Prediction
        """
        pass


if __name__ == '__main__':
    unittest.main()
