# coding: utf-8

"""
    Gene ontology api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from gene_ontology_microservice.models.go_confidence_response import GoConfidenceResponse

class TestGoConfidenceResponse(unittest.TestCase):
    """GoConfidenceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoConfidenceResponse:
        """Test GoConfidenceResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoConfidenceResponse`
        """
        model = GoConfidenceResponse()
        if include_optional:
            return GoConfidenceResponse(
                name = '',
                confidence = 1.337
            )
        else:
            return GoConfidenceResponse(
                name = '',
                confidence = 1.337,
        )
        """

    def testGoConfidenceResponse(self):
        """Test GoConfidenceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
