# coding: utf-8

"""
    Conformations api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from conformations_microservice.models.run_gromacs_simulations_request import \
    RunGromacsSimulationsRequest


class TestRunGromacsSimulationsRequest(unittest.TestCase):
    """RunGromacsSimulationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunGromacsSimulationsRequest:
        """Test RunGromacsSimulationsRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RunGromacsSimulationsRequest`
        """
        model = RunGromacsSimulationsRequest()
        if include_optional:
            return RunGromacsSimulationsRequest(
                temperature_k = 1.337,
                friction_coeff = 1.337,
                step_size = 1.337,
                integrator = 'LangevinIntegator',
                take_frame_every = 56,
                total_frames = 56,
                top = '',
                gro = ''
            )
        else:
            return RunGromacsSimulationsRequest(
                top = '',
                gro = '',
        )
        """

    def testRunGromacsSimulationsRequest(self):
        """Test RunGromacsSimulationsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
