# coding: utf-8

"""
    Conformations api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from conformations_microservice.models.open_mm_water_force_fields import \
    OpenMmWaterForceFields


class TestOpenMmWaterForceFields(unittest.TestCase):
    """OpenMmWaterForceFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenMmWaterForceFields(self):
        """Test OpenMmWaterForceFields"""
        # inst = OpenMmWaterForceFields()


if __name__ == "__main__":
    unittest.main()
