# coding: utf-8

"""
    Conformations api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from conformations_microservice.models.gen_gro_top_response import GenGroTopResponse

class TestGenGroTopResponse(unittest.TestCase):
    """GenGroTopResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenGroTopResponse:
        """Test GenGroTopResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenGroTopResponse`
        """
        model = GenGroTopResponse()
        if include_optional:
            return GenGroTopResponse(
                gro = '',
                top = '',
                errors = [
                    ''
                    ]
            )
        else:
            return GenGroTopResponse(
                gro = '',
                top = '',
        )
        """

    def testGenGroTopResponse(self):
        """Test GenGroTopResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
