# coding: utf-8

"""
    RoseTTAFold API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rosettafold_microservice.models.a3_m import A3M


class TestA3M(unittest.TestCase):
    """A3M unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> A3M:
        """Test A3M
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `A3M`
        """
        model = A3M()
        if include_optional:
            return A3M(
            )
        else:
            return A3M(
        )
        """

    def testA3M(self):
        """Test A3M"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
