from nolabs.application.folding.workflow import EsmfoldLightComponent, EsmfoldComponent
from nolabs.workflow.core.component import ComponentTypeFactory

ComponentTypeFactory.add_type(EsmfoldLightComponent)
ComponentTypeFactory.add_type(EsmfoldComponent)