name: biobuddy
run-name: biobuddy

# Build and push nolabs image using GitHub Cache API
# Only if relevant files were changed

on:
  push:
    branches:
      - master
    paths:
      - 'microservices/biobuddy/**'

jobs:
  build-and-push:
    if: github.repository == 'BasedLabs/NoLabs'

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-and-push-image.yaml
    with:
      microservice_name: "biobuddy"
      push: true
