name: Build and push docker image

on:
  workflow_call:
    inputs:
      microservice_name:
        required: true
        type: string
        description: "Specify microservice name from compose.yaml"
      push:
        required: true
        type: boolean
        description: "Whether to push docker image to ghcr"

env:
  IMAGE_TAG: ''
  BUILD_CONTEXT: ''

jobs:
  build-and-push:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Delete hostedtoolscache
        run: rm -rf /opt/hostedtoolcache

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install pyyaml python package
        run: pip install pyyaml

      - name: Get image name
        run: |
          echo "IMAGE_TAG=$(python .github/scripts/parse_compose_service_image.py ${{ inputs.microservice_name }})" >> $GITHUB_ENV

      - name: Get image build context
        run: |
          echo "BUILD_CONTEXT=$(python .github/scripts/parse_compose_service_build_context.py ${{ inputs.microservice_name }})" >> $GITHUB_ENV

      - name: Image name
        run: echo "$IMAGE_TAG"

      - name: Build context
        run: echo "$BUILD_CONTEXT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_CONTEXT }}
          file: ${{ env.BUILD_CONTEXT }}/build/Dockerfile
          push: ${{ inputs.push }}
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

