name: conformations
run-name: conformations

# Build and push nolabs image using GitHub Cache API
# Only if relevant files were changed

on: workflow_dispatch

jobs:
  build:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-docker.yaml
    with:
      microservice_name: "conformations"

  push:
    if: github.repository == 'BasedLabs/NoLabs'
    needs: build

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/push-docker.yaml
    with:
      microservice_name: "conformations"
