name: With server
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install pytorch
        run: pip install torch==1.13.1 torchvision torchaudio
      - name: Install torchgeometric
        run: pip install torch-geometric
      - name: Install additional deps
        run: pip install --no-index pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-1.13.0+cpu.html
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Start backend server
        working-directory: src/server
        run: PYTHONPATH=/home/runner/work/NoLabs/NoLabs python run.py --host=127.0.0.1 --port=5000 --test=True &
      - name: Install deps
        working-directory: src/server/frontend
        run: npm install
      - name: Run frontend
        working-directory: src/server/frontend
        run:  npm run dev &
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests
