name: With server
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Start backend server
        working-directory: src/server
        run: PYTHONPATH=/home/runner/work/NoLabs/NoLabs python run.py --host=127.0.0.1 --port=5000
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests
