name: With server
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: pip install --no-cache-dir -r requirements.txt && python src/server/run.py --host=127.0.0.1 --port=5000
          working-directory: tests
