name: With server
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clean space
        run: ./free_disk_space_github.sh
        shell: bash
      - name: Build docker container
        run: docker build -t nolabs -f Dockerfile .
      - name: Run docker container
        run: docker run --name nolabs-docker -d -p 5173:5173 -p 5000:5000 -e --test nolabs
      - name: Wait for the backend
        run: | 
          while true; do \
            output=$(docker logs nolabs-docker --since 4s)
            echo $output
            if echo "$output" | grep -q -- "Running on all addresses (0.0.0.0)"; then
              echo "$output"
              echo "Stopping action, since flask is running"
              break
            fi
            sleep 3  # Sleep for 1 second before checking again
          done
      - name: Check curl
        run: curl http://localhost:5000/api/amino-acid/experiments
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests


