name: With server
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clean space
        run: ./free_disk_space_github.sh
        shell: bash
      - name: Build docker container
        run: OUTPUT=$(docker build -t nolabs -f Dockerfile .)
      - name: Run docker container
        run: docker run -d -p 5173:5173 -p 5000:5000 -e --test nolabs
      - name: Show docker container output
        run: curl http://127.0.0.1:5000/api/amino-acid/experiments 2>/dev/null || true
      - name: Show docker container output
        run: docker logs $OUTPUT
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests


