name: esmfold-light-pr
run-name: esmfold-light-pr

# Build and push nolabs image using GitHub Cache API
# Only if relevant files were changed

on:
  pull_request:
    branches:
      - master
    paths:
      - 'microservices/esmfold_light/**'

jobs:
  build:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-docker.yaml
    with:
      microservice_name: "esmfold-light"
