name: external-data-query-pr
run-name: external-data-query-pr

# Build and push nolabs image using GitHub Cache API
# Only if relevant files were changed

on:
  pull_request:
    branches:
      - master
    paths:
      - 'microservices/external_data_query/**'

jobs:
  build:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-docker.yaml
    with:
      microservice_name: "external-data-query"
