name: gene_ontology-pr
run-name: gene_ontology-pr

# Build and push nolabs image using GitHub Cache API
# Only if relevant files were changed

on:
  pull_request:
    branches:
      - master
    paths:
      - 'microservices/gene_ontology/**'

jobs:
  build:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-docker.yaml
    with:
      microservice_name: "gene_ontology"