name: NoLabs push

on:
  push:
    branches: feature/cicd

env:
  OWN_REPO: github.repository = 'BasedLabs/NoLabs'

jobs:
  nolabs-push:
    needs: nolabs-build

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/push-docker.yaml
    with:
      microservice_name: "nolabs"
      push: ${{ env.OWN_REPO }}