name: nolabs
run-name: nolabs

# Build and push nolabs image using GitHub Cache API
# Only if relevant files were changed

on:
  pull_request:
    branches:
      - master
    paths:
      - 'build/**'
      - 'client/**'
      - 'frontend/**'
      - 'nolabs/**'
      - 'build/**'
      - 'pyproject.toml'
      - 'poetry.toml'

jobs:
  build:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-and-push-image.yaml
    with:
      microservice_name: "nolabs"
      push: false
